runtime: nodejs20

instance_class: F1

env_variables:
  NODE_ENV: "production"

entrypoint: node index.js

automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 0
  max_instances: 2

handlers:
  - url: /.*
    secure: always
    script: auto
